### ISSUE TITLE
Capture high-level business needs

### ISSUE THREAD

**Issue by jsabol** [CRGTMobile/electric-eel#6]

**Comment by lnewlen86** [comment]
this looks like a duplicate

**Comment by lnewlen86** [comment]
drafts accomplished by writing the process flow background and the user personas.

**Comment by lnewlen86** [comment]
other business descriptions are: 
-Reduced workforce by 74% in the past 35 years
-Many retired employees have come back to part-time contracting work (due to lost knowledge)
-Industrial, blue-collar feel due to in-house printing operations
-Countrys’s largest (and one of the oldest) in-plant facilities
-name change proposed by Director Davita Vance-Cooks ayear ago
-  Davita Vance-Cooks is the the first female as Public Printer to oversee GPO
